// Generated by CoffeeScript 1.7.1
var application, digitalocean, digitalocean_credentials, express, server;

express = require('express');

application = new express();

digitalocean_credentials = require('./config.json').nautical;

digitalocean = require('nautical').getClient(digitalocean_credentials);

application.get('/droplets', function(request, response) {
  console.log('Droplets');
  return digitalocean.droplets.list(function(error, reply) {
    console.log(reply.body);
    return response.send(JSON.stringify(reply.body));
  });
});

application.post('/droplets', function(request, response) {
  var droplet_data;
  droplet_data = {
    name: 'test',
    region: 'ams1',
    size: '512mb',
    image: '5141286'
  };
  console.log("Droplet create");
  console.log(droplet_data);
  return digitalocean.droplets.create(droplet_data, function(error, reply) {
    console.log(reply.body);
    return response.send(JSON.stringify(reply.body));
  });
});

application.get('/regions', function(request, response) {
  console.log('Regions');
  return digitalocean.regions.list(function(error, reply) {
    console.log(reply.body);
    return response.send(JSON.stringify(reply.body));
  });
});

application.get('/images', function(request, response) {
  console.log('Images');
  return digitalocean.images.list(function(error, reply) {
    console.log(reply.body);
    return response.send(JSON.stringify(reply.body));
  });
});

application.get('/sizes', function(request, response) {
  console.log('Sizes');
  return digitalocean.sizes.list(function(error, reply) {
    console.log(reply.body);
    return response.send(JSON.stringify(reply.body));
  });
});

server = application.listen(8000, function() {
  return console.log("Listening on port " + (server.address().port));
});

//# sourceMappingURL=index.map
